export 'package:veegil_accessment/view/screens/auth/login_screen.dart';
export 'package:veegil_accessment/view/screens/onboarding/splash_screen.dart';
export 'package:veegil_accessment/view/screens/auth/create_account_screen.dart';
export 'package:veegil_accessment/view/screens/dashboard/all_trx_screen.dart';
export 'package:veegil_accessment/view/screens/dashboard/deposit_trx_screen.dart';
export 'package:veegil_accessment/view/screens/dashboard/withdrawal_trx_screen.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export  'package:flutter/material.dart';
export 'package:veegil_accessment/config/app_strings.dart';
// export 'package:veegil_accessment/view/screens/auth/verify_email_screen.dart';
// export  'package:veegil_accessment/view/screens/auth/reset_password_screens/reset_password_screen.dart';